export const STRINGS = {
    answer: "Answer",
    howDoesItFeel: "How well did you know this?",
    numberOne: 1,
    numberTwo: 2,
    numberThree: 3,
    numberFour: 4,
    numberFive: 5,
    following: "Following",
    foryou: "For you",
    home: "Home",
    discover: "Discover",
    profile: "Profile",
    search: "Search",
    bookmark: "Bookmark",
    activity: "Activity",
    add: 140,
    bookmarkNumber: 140,
    share: 140,
    comment: 140,
    like: 140,
    flip: 140,
}